export const initialState = {
  ownerDetails: [
    {
      id: 0,
      "owner-actionDescription": "",
      ownerId: "",
      ownerName: "",
      "owner-comments": "",
      "owner-target-closure-date": "",
    },
  ],
  riskForum: [],
  category: "",
  sbu: "",
  account: "",
  projectId: "",
  severity: "",
  region: "",
  location: "",
  rootCause: "",
  itemDescription: "",
  risk: "",
  totalFTEs: "",
  impactArea: "",
  issueResolutionDate: "",
  businessImpact: "",
  status: "",
  dhdIssueId: "",
  revenueImpact: "",
  marginImpact: "",
};
